/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MapBan {
	teamA: string;
	teamB: string;
	bestOf: number;
	map1?: string;
	map2?: string;
	map3?: string;
	map4?: string;
	map5?: string;
	map6?: string;
	map7?: string;
}
